### ISSUE TITLE
Unable to run random agent

### ISSUE THREAD

**Issue by suhani247** [deepmind/android_env#120]
Hi I'm trying to run the random agent with one of the existing test protos. But my execution just stays at the line "creating grpc channel" and doesn't move on from there. 
OS: Ubuntu 22.04
Python- python 3.9.16

**Comment by kenjitoyama** [comment]
Hi @suhani247 , we need more information. Please attach logs to this bug.

Also, please use the github version. The version from PyPy is super outdated. Thanks!

**Comment by kenjitoyama** [comment]
Hi, I'll close this for now. Thanks.

**Comment by HahmDY** [comment]
I have similar issue. For waiting, I set the startup_wait_time_sec=600 but it doesn't work.

**Comment by kenjitoyama** [comment]
Hello HahmDongyoon,

Please see my reply at
https://github.com/google-deepmind/android_env/issues/200 and let me know
how it goes.

Cheers,

Daniel
