### ISSUE TITLE
Running on Docker

### ISSUE THREAD

**Issue by NaxAlpha** [deepmind/android_env#18]
Hi,

Thanks for the great work. I want to ask if it is possible to integrate it with Android docker image like [this one](https://github.com/budtmo/docker-android). It would allow a much more cleaner setup.

Thanks

**Comment by kenjitoyama** [comment]
Hello @NaxAlpha. Yes, definitely possible, but we don't support it. It boils down to implementing a [Simulator](https://github.com/deepmind/android_env/blob/cf5f6318c4507d350c4b90aeffb6950d5b7bd9dc/android_env/components/base_simulator.py#L30) that can talk to the docker container to obtain screenshots and to send touchscreen actions.

Notice that AndroidEnv runs _outside_ of Android so it's agnostic to actual Android dynamics which today are generated by the Android Emulator.

**Comment by NaxAlpha** [comment]
Thanks - will look into that!
