### ISSUE TITLE
1V1 environmnet

### ISSUE THREAD

**Issue by sheng-han-zhang** [deepmind/android_env#20]
Hi ,

    Thank you very much for giving such a nice tool. I just have one problem, will you offer some compatible 1v1 environments in the future? For example, in current Pong and droidfish chess, we can train an rl-agent against built-in bots. But you know, we need the help of selfplay to get a stronger rl-agent.
    Besides, will you also consider environments that need two ro more players to coorparate?
    Thanks.

Regards,
Shenghan

**Comment by kenjitoyama** [comment]
Hello @sheng-han-zhang!

When we run multiplayer environments, we usually introduce a layer above the actual environment to coordinate the process. This layer usually prepares the observation for each player, receives their actions and forwards them to the environment. We currently don't have this for AndroidEnv and are not working on it, but we are generally not against the idea. The bots in the current tasks are actually already challenging for most agents, and we'd like to tackle those first before thinking of going way beyond them. ;)

I hope this helps,

Cheers,

Daniel

**Comment by sheng-han-zhang** [comment]
Hi Daniel,
       Thank you very much for your detailed reply.
       You are right the current tasks are already challenging enough. Hope can hear more good news from you in the future.
Best,
Shenghan
