### ISSUE TITLE
Old problems in master

### ISSUE THREAD

**Issue by davendiy** [deepmind/android_env#25]
Hello, 
There was an issue [Crash on "run_acme_agent.py" #17](https://github.com/deepmind/android_env/issues/17), that is currently closed and marked as fixed, but the [version cf5f631](https://github.com/deepmind/android_env/commit/cf5f6318c4507d350c4b90aeffb6950d5b7bd9dc) which comments are referring to doesn't belong to the project. As far as I understand the problem is due to the force [initial commit](https://github.com/deepmind/android_env/commit/7094c09273aaf64e5479b67840f681e66aa57f3f), which didn't have the oldest fixes. Can you please merge these changes in the master branch? 
Thank you in advance.

**Comment by kenjitoyama** [comment]
Hi @davendiy , sorry for the massive delay. That forced initial commit was my error a while ago (it was a stupid error when trying to update https://github.com/deepmind/envlogger). Either way, I actually had to do another forced commit to get Copybara to play nicely with Github, and I think the system has been working well for the past couple of months. I'll close this issue, but let us know if you encounter other things. Thanks!
