### ISSUE TITLE
Extras not always returned . ( in case of floodit_basic).

### ISSUE THREAD

**Issue by anshmn** [deepmind/android_env#27]
I tried to print The extras using  logging.info('***********Extras*********: %r ', env.task_extras())  in thr run_human_agent.py and found out that sometimes , it does print the corrent extras whereas quite often it just prints an empty dictionary!. 
Could you please point out any possible reasons for it. 
Any help would be greatly appreciated.
Regards

**Comment by kenjitoyama** [comment]
Hi @anshmn, we only print the latest extras at a particular point in time. That is, if an extra comes at timestep `t` and no extras are produced after that, timestep `t+1` will not contain task extras. Does that make sense to you? Thanks!
