### ISSUE TITLE
Acme example for AndroidEnv requires `reverb` (Linux only)

### ISSUE THREAD

**Issue by 8bitmp3** [deepmind/android_env#7]
The Acme [`run_acme_agent.py`](https://github.com/deepmind/android_env/blob/main/examples/run_acme_agent.py) example appears to require [`/deepmind/reverb`](https://github.com/deepmind/reverb) but that package - can only run on Linux systems at the moment:

> ⚠️ Reverb currently only supports Linux based OSes.

(from https://github.com/deepmind/reverb)

Core Acme installation:

```
pip install dm-acme
pip install dm-acme[reverb]
```

(https://github.com/deepmind/acme)

**Comment by AlphaSue** [comment]
@kenjitoyama Hi, is there any examples to build the wrap the environment without using acme, since it only support linux

**Comment by kenjitoyama** [comment]
Hello @AlphaSue! I'm not sure I understand your question. What do you mean by "build the wrapper of the environment"?

As @8bitmp3 stated above, to run Acme agents, you'll need to be on Linux until Reverb is supported in other platforms. We also have a [random agent](https://github.com/deepmind/android_env/blob/main/examples/run_random_agent.py) script you can use to load the environment and use as base to create your own RL agents.

Cheers!

**Comment by AlphaSue** [comment]
@kenjitoyama I solved that problem by looking at the random agent. I'm wondering if I can install other interested apps like league of legends as an Enviroment to train agent?

Thx!

**Comment by kenjitoyama** [comment]
Yes, you can install whatever you want. AndroidEnv places no restriction on which apps you want to use for training, but if the app emits no messages at all in logcat you'll have no rewards, which will make the training very tricky. Please see the [task guide](https://github.com/deepmind/android_env/blob/main/docs/tasks_guide.md) for more details about setting up a task.
